name: Docker Compose CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and run Docker Compose
      - name: Build and start services
        run: |
          docker-compose up --build -d

      # Wait for services to become healthy
      - name: Wait for services to become healthy
        run: |
          docker-compose ps
          timeout=60
          until [ "$(docker-compose ps -q | xargs docker inspect -f '{{.State.Health.Status}}' | grep -c healthy)" -eq "$(docker-compose ps -q | wc -l)" ]; do
            sleep 5
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for services to become healthy"
              docker-compose logs
              exit 1
            fi
          done

      # Verify logs for all services (optional)
      - name: Show logs for all services
        run: docker-compose logs

      # Stop and clean up services
      - name: Stop and remove containers
        run: docker-compose down
